name: Continuous integration
on:
  push:
    branches-ignore:
      - "main"
  pull_request:
jobs:
  check-format:
    runs-on: ubuntu-latest
    container: python:3.13-slim
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4
      - name: Install uv
        uses: astral-sh/setup-uv@v5
      - name: Sync venv
        run: |
          apt update && apt install -y \
            gcc \
            libtss2-dev \
            pkgconf
          uv sync --group=dev
      - name: Run format check
        run: uv run ruff format --check
  check-lint:
    runs-on: ubuntu-latest
    container: python:3.13-slim
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4
      - name: Install uv
        uses: astral-sh/setup-uv@v5
      - name: Sync venv
        run: |
          apt update && apt install -y \
            gcc \
            libtss2-dev \
            pkgconf
          uv sync --group=dev
      - name: Run lint check
        run: uv run ruff check --no-fix
  check-typing:
    runs-on: ubuntu-latest
    container: python:3.13-slim
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4
      - name: Install uv
        uses: astral-sh/setup-uv@v5
      - name: Sync venv
        run: |
          apt update && apt install -y \
            gcc \
            libtss2-dev \
            pkgconf
          uv sync --group=dev
      - name: Run type check
        run: uv run mypy src/
